/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Felipe
 */
public class BotoesCrudCliente extends javax.swing.JPanel {

    /**
     * Creates new form BotoesCrudCliente
     */
    public BotoesCrudCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crudClienteBotaoCadastrar = new javax.swing.JButton();
        crudClienteBotaoAtualizar = new javax.swing.JButton();
        crudClienteBotaoRemover = new javax.swing.JButton();

        crudClienteBotaoCadastrar.setText("Cadastrar");

        crudClienteBotaoAtualizar.setText("Atualizar");
        crudClienteBotaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudClienteBotaoAtualizarActionPerformed(evt);
            }
        });

        crudClienteBotaoRemover.setText("Remover");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crudClienteBotaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(crudClienteBotaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crudClienteBotaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crudClienteBotaoCadastrar)
                    .addComponent(crudClienteBotaoAtualizar)
                    .addComponent(crudClienteBotaoRemover))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crudClienteBotaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudClienteBotaoAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crudClienteBotaoAtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crudClienteBotaoAtualizar;
    private javax.swing.JButton crudClienteBotaoCadastrar;
    private javax.swing.JButton crudClienteBotaoRemover;
    // End of variables declaration//GEN-END:variables
}
